# Generated by Django 3.1.3 on 2021-06-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210623_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='comment_images', to='users.Picture'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='post_images', to='users.Picture'),
        ),
    ]
