# Generated by Django 3.1.3 on 2021-08-06 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210804_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='booked_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='booked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
