# Generated by Django 3.1.3 on 2021-08-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210809_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='pub_date',
        ),
    ]
