# Generated by Django 3.1.3 on 2021-08-19 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210811_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='_account_subscribed_to_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
