# Generated by Django 3.1.3 on 2021-08-20 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_account_subscribed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
