# Generated by Django 3.1.3 on 2021-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210820_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
